server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: BookSelling
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/book_selling_system"
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  signer-key: ""
  valid-duration: 3600 #in seconds
  refresh-duration: 36000 # in seconds